- name: "Cam\xE9ra thermique didactique"
  price_excluding_tax: "983,33\_\u20AC"
  price_including_tax: "1\u202F180,00\_\u20AC"
  sku: N/A
  url: https://jeulin.com/jeulin_fr/577001.html
- name: "Pile 9 V type 6F22 alcaline (\xE0 l'unit\xE9)"
  price_excluding_tax: "2,92\_\u20AC"
  price_including_tax: "3,50\_\u20AC"
  sku: N/A
  url: https://jeulin.com/jeulin_fr/283551.html
- name: "Douille E10 \xE0 DEL"
  price_excluding_tax: "13,25\_\u20AC"
  price_including_tax: "15,90\_\u20AC"
  sku: N/A
  url: https://jeulin.com/jeulin_fr/280330.html
- name: Douille E10
  price_excluding_tax: "12,42\_\u20AC"
  price_including_tax: "14,90\_\u20AC"
  sku: N/A
  url: https://jeulin.com/jeulin_fr/283044.html
- name: "Pile saline 6F22 - 9 V (\xE0 l'unit\xE9)"
  price_excluding_tax: "1,13\_\u20AC"
  price_including_tax: "1,36\_\u20AC"
  sku: N/A
  url: https://jeulin.com/jeulin_fr/283547.html
- name: "Pile alcaline 3LR12 - 4,5 V (\xE0 l'unit\xE9)"
  price_excluding_tax: "3,75\_\u20AC"
  price_including_tax: "4,50\_\u20AC"
  sku: N/A
  url: https://jeulin.com/jeulin_fr/751300.html
- name: Moteur sur support
  price_excluding_tax: "13,25\_\u20AC"
  price_including_tax: "15,90\_\u20AC"
  sku: N/A
  url: https://jeulin.com/jeulin_fr/283045.html
- name: "Interrupteur \xE0 levier sur support"
  price_excluding_tax: "12,42\_\u20AC"
  price_including_tax: "14,90\_\u20AC"
  sku: N/A
  url: https://jeulin.com/jeulin_fr/283042.html
- name: "Pile alcaline 9 V type 6F22 (\xE0 l\u2019unit\xE9) - ENERGIZER"
  price_excluding_tax: "6,00\_\u20AC"
  price_including_tax: "7,20\_\u20AC"
  sku: N/A
  url: https://jeulin.com/jeulin_fr/283556.html
- name: "Pinces crocodiles \xE0 vis non isol\xE9es (Lot de 10)"
  price_excluding_tax: "4,08\_\u20AC"
  price_including_tax: "4,90\_\u20AC"
  sku: N/A
  url: https://jeulin.com/jeulin_fr/283277.html
- name: "Jeu de 5 cylindres de volume \xE9gal"
  price_excluding_tax: "19,17\_\u20AC"
  price_including_tax: "23,00\_\u20AC"
  sku: N/A
  url: https://jeulin.com/jeulin_fr/312044.html
- name: Piles alcalines LR06 AA (Lot de 10)
  price_excluding_tax: "8,00\_\u20AC"
  price_including_tax: "9,60\_\u20AC"
  sku: N/A
  url: https://jeulin.com/jeulin_fr/283550.html
- name: "Adaptateur BNC- Banane de s\xE9curit\xE9"
  price_excluding_tax: "11,57\_\u20AC"
  price_including_tax: "13,88\_\u20AC"
  sku: N/A
  url: https://jeulin.com/jeulin_fr/293052.html
- name: "Bloc alimentation \xE0 d\xE9coupage 12V - 600 mA"
  price_excluding_tax: "13,00\_\u20AC"
  price_including_tax: "15,60\_\u20AC"
  sku: N/A
  url: https://jeulin.com/jeulin_fr/281612.html
- name: "R\xE9cepteur Moduson 2"
  price_excluding_tax: "49,17\_\u20AC"
  price_including_tax: "59,00\_\u20AC"
  sku: N/A
  url: https://jeulin.com/jeulin_fr/222078.html
- name: Boussole simple
  price_excluding_tax: "3,25\_\u20AC"
  price_including_tax: "3,90\_\u20AC"
  sku: N/A
  url: https://jeulin.com/jeulin_fr/263014.html
- name: "Mallette Microcontr\xF4leur Arduino Python  Seconde et Premi\xE8re Physique-Chimie"
  price_excluding_tax: "165,83\_\u20AC"
  price_including_tax: "199,00\_\u20AC"
  sku: N/A
  url: https://jeulin.com/jeulin_fr/276903.html
- name: "\xC9lectrodes en graphite (charbon) (Lot de 2)"
  price_excluding_tax: "2,92\_\u20AC"
  price_including_tax: "3,50\_\u20AC"
  sku: N/A
  url: https://jeulin.com/jeulin_fr/283088.html
