from sqlalchemy import text


class FonctionsGlobales:
            
    class Delete:

        def delete_all(cnx):
            """ Delete tout sauf le contenu des tables UTILISATEUR, STATUT et 2FA; 
            Ne supprime pas vraiment STOCKLABORATOIRE : SET toutes les quantités à 0"""
            script = "DELETE FROM RISQUES;DELETE FROM RESERVELABORATOIRE;UPDATE STOCKLABORATOIRE SET QUANTITE=0;DELETE FROM ENVOIFOURNISSEUR;DELETE FROM SUIVICOMMANDE;DELETE FROM AJOUTERMATERIEL;DELETE FROM RECHERCHEMATERIELS;DELETE FROM ALERTESENCOURS;DELETE FROM MATERIELUNIQUE;DELETE FROM COMMANDE;DELETE FROM MATERIEL;DELETE FROM ARCHIVECOMMANDE;DELETE FROM ARCHIVEBONCOMMANDE;DELETE FROM ARCHIVECOMMANDEANCIEN;DELETE FROM FOURNISSEUR;DELETE FROM RANGEMENT;DELETE FROM ENDROIT;DELETE FROM CATEGORIE;DELETE FROM DOMAINE;DELETE FROM RISQUE;DELETE FROM FDS;DELETE FROM BONCOMMANDE;DELETE FROM DEMANDE;DELETE FROM ETATCOMMANDE;DELETE FROM TYPESALERTES;"
            cnx.execute(text(script))
            cnx.commit()


